# Generated by Django 4.0 on 2022-01-24 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0016_alter_equipo_fu_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criticidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eppop', models.PositiveIntegerField(choices=[('1', 'SI'), ('0', 'NO')], default=0, verbose_name='¿ES PARTE DE UN PROCESO OPERATIVO PRINCIPAL?')),
                ('psistema', models.PositiveIntegerField(choices=[('1', 'SI'), ('0', 'NO')], default=0, verbose_name='¿ES PARTE DE UN SISTEMA?')),
                ('fanual', models.PositiveIntegerField(choices=[('1', 'SI'), ('0', 'NO')], default=0, verbose_name='¿SE HA PRODUCIDO ALGUNA FALLA EN EL ÚLTIMO AÑO?')),
                ('afeconomica', models.PositiveIntegerField(choices=[('1', 'SI'), ('0', 'NO')], default=0, verbose_name='¿SU PÉRDIDA DE FUNCIÓN PUEDE PRODUCIR AFECTACIÓN ECONÓMICA?')),
                ('afsalud', models.PositiveIntegerField(choices=[('1', 'SI'), ('0', 'NO')], default=0, verbose_name='¿SU PÉRDIDA DE FUNCIÓN PUEDE PRODUCIR AFECTACIÓN A LA SALUD DEL PERSONAL?')),
                ('afambiental', models.PositiveIntegerField(choices=[('1', 'SI'), ('0', 'NO')], default=0, verbose_name='¿SU PÉRDIDA DE FUNCIÓN PUEDE PRODUCIR AFECTACIÓN AL MEDIO AMBIENTE?')),
                ('redundancia', models.PositiveIntegerField(verbose_name='REDUNDANCIA')),
                ('crit_pacial', models.FloatField(default=0.0, verbose_name='CRITICIDAD PARCIAL')),
                ('crit_total', models.FloatField(default=0.0, verbose_name='CRITICIDAD TOTAL')),
                ('ingresado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.equipo')),
            ],
        ),
    ]
