# Generated by Django 4.0 on 2022-01-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticidad', '0002_criticidad_eval_redun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticidad',
            name='afambiental',
        ),
        migrations.RemoveField(
            model_name='criticidad',
            name='afeconomica',
        ),
        migrations.RemoveField(
            model_name='criticidad',
            name='afsalud',
        ),
        migrations.RemoveField(
            model_name='criticidad',
            name='eppop',
        ),
        migrations.RemoveField(
            model_name='criticidad',
            name='fanual',
        ),
        migrations.RemoveField(
            model_name='criticidad',
            name='psistema',
        ),
        migrations.RemoveField(
            model_name='criticidad',
            name='redundancia',
        ),
        migrations.AddField(
            model_name='criticidad',
            name='fua',
            field=models.PositiveIntegerField(choices=[(1, 'SI'), (0, 'NO')], default=0, verbose_name='¿SE HA PRODUCIDO ALGUNA FALLA EN EL ÚLTIMO AÑO?'),
        ),
        migrations.AddField(
            model_name='criticidad',
            name='ma',
            field=models.PositiveIntegerField(choices=[(1, 'SI'), (0, 'NO')], default=0, verbose_name='¿SU PÉRDIDA DE FUNCIÓN PUEDE PRODUCIR AFECTACIÓN AL MEDIO AMBIENTE?'),
        ),
        migrations.AddField(
            model_name='criticidad',
            name='pe',
            field=models.PositiveIntegerField(choices=[(1, 'SI'), (0, 'NO')], default=0, verbose_name='¿SU PÉRDIDA DE FUNCIÓN PUEDE PRODUCIR AFECTACIÓN ECONÓMICA?'),
        ),
        migrations.AddField(
            model_name='criticidad',
            name='po',
            field=models.PositiveIntegerField(choices=[(1, 'SI'), (0, 'NO')], default=0, verbose_name='¿ES PARTE DE UN PROCESO OPERATIVO PRINCIPAL?'),
        ),
        migrations.AddField(
            model_name='criticidad',
            name='ps',
            field=models.PositiveIntegerField(choices=[(1, 'SI'), (0, 'NO')], default=0, verbose_name='¿ES PARTE DE UN SISTEMA?'),
        ),
        migrations.AddField(
            model_name='criticidad',
            name='r',
            field=models.PositiveIntegerField(choices=[(1, 'SI'), (0, 'NO')], default=0, verbose_name='REDUNDANCIA'),
        ),
        migrations.AddField(
            model_name='criticidad',
            name='sh',
            field=models.PositiveIntegerField(choices=[(1, 'SI'), (0, 'NO')], default=0, verbose_name='¿SU PÉRDIDA DE FUNCIÓN PUEDE PRODUCIR AFECTACIÓN A LA SALUD DEL PERSONAL?'),
        ),
    ]
