# Generated by Django 4.0 on 2022-01-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criticidad', '0003_remove_criticidad_afambiental_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticidad',
            old_name='ingresado',
            new_name='ingres',
        ),
        migrations.RenameField(
            model_name='criticidad',
            old_name='modificado',
            new_name='modif',
        ),
    ]
