# Generated by Django 4.0 on 2022-01-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticidad', '0004_rename_ingresado_criticidad_ingres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticidad',
            name='crit_pacial',
            field=models.FloatField(default=0.0, editable=False, verbose_name='CRITICIDAD PARCIAL'),
        ),
        migrations.AlterField(
            model_name='criticidad',
            name='crit_total',
            field=models.FloatField(default=0.0, editable=False, verbose_name='CRITICIDAD TOTAL'),
        ),
        migrations.AlterField(
            model_name='criticidad',
            name='eval_redun',
            field=models.PositiveIntegerField(default=0.0, editable=False, verbose_name='EVAL REDUNDANCIA'),
        ),
    ]
