# Generated by Django 4.0 on 2022-01-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0018_delete_activo'),
        ('criticidad', '0007_alter_criticidad_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticidad',
            name='activo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.equipo'),
        ),
    ]
