# Generated by Django 4.0 on 2022-02-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticidad', '0008_alter_criticidad_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticidad',
            name='crit_pacial',
            field=models.FloatField(default=0.0, verbose_name='CRITICIDAD PARCIAL'),
        ),
        migrations.AlterField(
            model_name='criticidad',
            name='crit_total',
            field=models.FloatField(default=0.0, verbose_name='CRITICIDAD TOTAL'),
        ),
        migrations.AlterField(
            model_name='criticidad',
            name='eval_redun',
            field=models.PositiveIntegerField(default=0.0, verbose_name='EVAL REDUNDANCIA'),
        ),
    ]
