# Generated by Django 4.0 on 2022-03-08 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0027_alter_planta_descripcion_and_more'),
        ('criticidad', '0012_criticidad_nombre_criticidadpr_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=70)),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='COSTO DE MANTENIMIENTO')),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=70)),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='EXPOSICIÓN')),
            ],
        ),
        migrations.CreateModel(
            name='MdA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=70)),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='MEDIO AMBIENTE')),
            ],
        ),
        migrations.CreateModel(
            name='Ocurrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=70)),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='OCURRENCIA')),
            ],
        ),
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=70)),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='PÉRDIDA DE PRODUCCIÓN')),
            ],
        ),
        migrations.CreateModel(
            name='Redundancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=70)),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='REDUNDANCIA')),
            ],
        ),
        migrations.CreateModel(
            name='Segysa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=70)),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='SEGURIDAD Y SALUD')),
            ],
        ),
        migrations.CreateModel(
            name='CriticidadCPr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, default='????', max_length=30)),
                ('locacion', models.CharField(blank=True, default='????', max_length=70, verbose_name='LOCACIÓN')),
                ('fallas', models.PositiveIntegerField(blank=True, default=0, verbose_name='NÚMERO DE FALLAS')),
                ('mtbf', models.PositiveIntegerField(blank=True, default=0, verbose_name='MTBF')),
                ('vdr', models.PositiveIntegerField(default=0.0, verbose_name='VALOR DE RIESGO')),
                ('ctdr', models.CharField(blank=True, max_length=30, verbose_name='CATEGORÍA DE RIESGO')),
                ('ingres', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('modif', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.equipoprincipal')),
                ('cm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.costo')),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.exposicion')),
                ('md', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.mda')),
                ('ocurrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.ocurrencia')),
                ('pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.perdida')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.redundancia')),
                ('segysa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.segysa')),
            ],
        ),
    ]
