# Generated by Django 4.0 on 2022-03-08 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0027_alter_planta_descripcion_and_more'),
        ('criticidad', '0014_alter_costo_valor_alter_exposicion_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticidadcpr',
            name='locacion',
            field=models.CharField(blank=True, max_length=70, verbose_name='LOCACIÓN'),
        ),
        migrations.AlterField(
            model_name='criticidadcpr',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='CriticidadCSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=30)),
                ('locacion', models.CharField(blank=True, max_length=70, verbose_name='LOCACIÓN')),
                ('fallas', models.PositiveIntegerField(blank=True, default=0, verbose_name='NÚMERO DE FALLAS')),
                ('mtbf', models.PositiveIntegerField(blank=True, default=0, verbose_name='MTBF')),
                ('vdr', models.PositiveIntegerField(default=0, verbose_name='VALOR DE RIESGO')),
                ('ctdr', models.CharField(blank=True, max_length=30, verbose_name='CATEGORÍA DE RIESGO')),
                ('ingres', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('modif', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.equipo')),
                ('cm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.costo')),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.exposicion')),
                ('md', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.mda')),
                ('ocurrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.ocurrencia')),
                ('pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.perdida')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.redundancia')),
                ('segysa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticidad.segysa')),
            ],
        ),
    ]
