# Generated by Django 4.0 on 2022-03-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticidad', '0015_alter_criticidadcpr_locacion_alter_criticidadcpr_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticidadcpr',
            name='nombre',
            field=models.CharField(blank=True, default='????', max_length=70),
        ),
        migrations.AddField(
            model_name='criticidadcsec',
            name='nombre',
            field=models.CharField(blank=True, default='????', max_length=70),
        ),
    ]
