# Generated by Django 4.0 on 2022-03-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0027_alter_planta_descripcion_and_more'),
        ('criticidad', '0017_alter_criticidadcpr_activo_alter_criticidadcpr_ctdr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticidadcpr',
            name='activo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.equipoprincipal'),
        ),
        migrations.AlterField(
            model_name='criticidadcpr',
            name='ctdr',
            field=models.CharField(blank=True, default='???', max_length=30, verbose_name='CATEGORÍA DE RIESGO'),
        ),
        migrations.AlterField(
            model_name='criticidadcpr',
            name='vdr',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='VALOR DE RIESGO'),
        ),
    ]
