# Generated by Django 4.0 on 2022-01-18 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Planta')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=70, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Sistema')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=70, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('nombre', models.CharField(max_length=70, verbose_name='Activo')),
                ('año', models.DateTimeField(verbose_name='Año de fabricación')),
                ('capacidad', models.CharField(max_length=70, verbose_name='Capacidad de Diseño/Operativa')),
                ('fu_mantenimiento', models.DateTimeField(verbose_name='Fecha de último mantenimiento integral')),
                ('estado', models.CharField(choices=[('O', 'Operativo'), ('F', 'Fuera de Servicio')], default='Masculino', max_length=9, verbose_name='Estado Operativo')),
                ('observaciones', models.CharField(max_length=10, verbose_name='Observaciones')),
                ('ingresado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='registro.planta')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='registro.sistema')),
            ],
        ),
    ]
