# Generated by Django 4.0 on 2022-01-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_sistema_planta_remove_activo_planta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='año',
            field=models.DateField(verbose_name='Año de fabricación'),
        ),
    ]
