# Generated by Django 4.0 on 2022-01-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_activo_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='planta',
            field=models.ManyToManyField(to='registro.Planta'),
        ),
    ]
