# Generated by Django 4.0 on 2022-01-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_sistema_planta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='planta',
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='planta',
        ),
        migrations.AddField(
            model_name='sistema',
            name='planta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='planta', to='registro.planta'),
            preserve_default=False,
        ),
    ]
