# Generated by Django 4.0 on 2022-01-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_asp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('nombre', models.CharField(max_length=70, verbose_name='Activo')),
                ('año', models.DateField(verbose_name='Año de fabricación')),
                ('capacidad', models.CharField(max_length=70, verbose_name='Capacidad de Diseño/Operativa')),
                ('fu_mantenimiento', models.DateTimeField(verbose_name='Fecha de último mantenimiento integral')),
                ('estado', models.CharField(choices=[('O', 'Operativo'), ('F', 'Fuera de Servicio')], default='Masculino', max_length=9, verbose_name='Estado Operativo')),
                ('observaciones', models.CharField(max_length=100, verbose_name='Observaciones')),
                ('ingresado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
        ),
        migrations.RemoveField(
            model_name='activo',
            name='año',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='fu_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='planta',
        ),
        migrations.AddField(
            model_name='activo',
            name='planta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro.planta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ASP',
        ),
        migrations.AddField(
            model_name='activo',
            name='activo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='registro.equipo'),
            preserve_default=False,
        ),
    ]
