# Generated by Django 4.0 on 2022-01-22 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_equipo_remove_activo_año_remove_activo_capacidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='sistema',
        ),
        migrations.AddField(
            model_name='activo',
            name='sistema',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='registro.sistema'),
            preserve_default=False,
        ),
    ]
