# Generated by Django 4.0 on 2022-01-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_remove_activo_sistema_activo_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='planta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='registro.planta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='sistema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro.sistema'),
            preserve_default=False,
        ),
    ]
