# Generated by Django 4.0 on 2022-01-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_equipo_planta_equipo_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codes',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
