# Generated by Django 4.0 on 2022-01-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_remove_equipo_codes_equipo_codigo_unico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='codigo_unico',
        ),
        migrations.AddField(
            model_name='equipo',
            name='codes',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('O', 'Operativo'), ('F', 'Fuera de Servicio')], default='Masculino', max_length=9, verbose_name='Estado Operativo'),
        ),
    ]
