# Generated by Django 4.0 on 2022-01-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_remove_equipo_codigo_unico_equipo_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fu_mantenimiento',
            field=models.DateField(verbose_name='Fecha de último mantenimiento integral'),
        ),
    ]
