# Generated by Django 4.0 on 2022-01-29 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0017_alter_equipo_codes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activo',
        ),
    ]
