# Generated by Django 4.0 on 2022-02-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0018_delete_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codes',
            field=models.CharField(default='????', max_length=70),
        ),
    ]
