# Generated by Django 4.0 on 2022-02-23 03:25

from django.db import migrations, models
import registro.models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0021_equipo_datasheet_alter_equipo_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='año',
            field=models.DateField(blank=True, null=True, verbose_name='Año de fabricación'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='datasheet',
            field=models.FileField(blank=True, upload_to='datasheets/', validators=[registro.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('O', 'Operativo'), ('F', 'Fuera de Servicio')], default='O', max_length=9, verbose_name='Estado Operativo'),
        ),
    ]
