# Generated by Django 4.0 on 2022-02-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0022_alter_equipo_año_alter_equipo_datasheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fu_mantenimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de último mantenimiento integral'),
        ),
    ]
