# Generated by Django 4.0 on 2022-03-03 20:34

from django.db import migrations, models
import registro.models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0023_alter_equipo_fu_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='datasheet',
            field=models.FileField(blank=True, upload_to='', validators=[registro.models.validate_file_extension]),
        ),
    ]
