# Generated by Django 4.0 on 2022-03-03 20:45

from django.db import migrations, models
import registro.models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0024_alter_equipo_datasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[registro.models.validate_file_extension], verbose_name='Datasheet'),
        ),
    ]
