# Generated by Django 4.0 on 2022-03-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0026_plantasecundaria_subsistema_equipo_codigo_de_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=70, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='plantasecundaria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=70, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='descripcion',
            field=models.CharField(blank=True, max_length=70, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='subsistema',
            name='descripcion',
            field=models.CharField(blank=True, max_length=70, verbose_name='Descripción'),
        ),
    ]
