# Generated by Django 4.0 on 2022-03-09 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0027_alter_planta_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='subsistema',
            field=models.ForeignKey(blank=True, default='---', on_delete=django.db.models.deletion.CASCADE, to='registro.subsistema'),
        ),
        migrations.AlterField(
            model_name='equipoprincipal',
            name='subsistema',
            field=models.ForeignKey(blank=True, default='---', on_delete=django.db.models.deletion.CASCADE, to='registro.subsistema'),
        ),
    ]
